"""
Feature request pipeline orchestrator — Phase 4.

run_feature_pipeline(fr_id, user_id) drives the full flow:
  pending → planning → coding → sandboxing → pushing → pr_opened | failed
"""
import json
import logging
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from backend.app.db import AsyncSessionLocal
from backend.app.models.feature_request import FeatureRequest
from backend.app.models.repo import Repo
from backend.app.models.settings import UserSettings
from backend.app.services.coder import generate_code
from backend.app.services.encryption import decrypt
from backend.app.services.git_push import create_github_pr, get_default_branch, push_fix_branch
from backend.app.services.planner import generate_plan
from backend.app.services.sandbox import run_sandbox

logger = logging.getLogger(__name__)

MAX_SANDBOX_LOG = 20_000  # chars stored in DB


def _restore_repo(repo_dir: Path, base_branch: str) -> None:
    try:
        import subprocess

        subprocess.run(
            ["git", "checkout", base_branch],
            cwd=str(repo_dir),
            capture_output=True,
            text=True,
            check=False,
        )
        subprocess.run(
            ["git", "reset", "--hard", f"origin/{base_branch}"],
            cwd=str(repo_dir),
            capture_output=True,
            text=True,
            check=False,
        )
    except Exception:
        pass


async def run_feature_pipeline(fr_id: str, user_id: str) -> None:
    """
    Full feature implementation pipeline for a single FeatureRequest.
    All status transitions are persisted so the frontend can poll.
    """
    async with AsyncSessionLocal() as db:
        fr = await _get_fr(fr_id, db)
        if not fr:
            logger.error("[feature] feature_request %s not found", fr_id)
            return

        repo = await _get_repo(fr.repo_id, db)
        us = await _get_settings(user_id, db)

        if not repo or not us:
            await _fail(fr, "Missing repo or user settings.", db)
            return

        repo_dir = Path("repos") / repo.id
        base_branch = repo.default_branch or "main"
        if not repo_dir.exists():
            await _fail(fr, f"Cloned repo directory not found: {repo_dir}", db)
            return

        # ── Step 1: Plan ──────────────────────────────────────────────────
        await _set_status(fr, "planning", db)
        try:
            plan = await generate_plan(fr.description, user_id, repo.id, db)
        except Exception as exc:
            await _fail(fr, f"Planning failed: {exc}", db)
            return

        fr.plan_json = json.dumps(plan)
        await db.commit()

        # ── Step 2: Code generation ───────────────────────────────────────
        await _set_status(fr, "coding", db)
        try:
            patches = await generate_code(plan, fr.description, user_id, repo.id, db)
        except Exception as exc:
            await _fail(fr, f"Code generation failed: {exc}", db)
            return

        fr.patches_json = json.dumps({k: v[:50_000] for k, v in patches.items()})
        await db.commit()

        # ── Step 3: Write patches to disk ─────────────────────────────────
        try:
            for file_path, content in patches.items():
                abs_path = repo_dir / file_path
                abs_path.parent.mkdir(parents=True, exist_ok=True)
                abs_path.write_text(content, encoding="utf-8")
        except Exception as exc:
            await _fail(fr, f"Cannot write files to disk: {exc}", db)
            return

        # ── Step 4: Sandbox ───────────────────────────────────────────────
        await _set_status(fr, "sandboxing", db)
        try:
            passed, sandbox_log = await run_sandbox(repo_dir)
        except Exception as exc:
            await _fail(fr, f"Sandbox error: {exc}", db)
            return

        fr.sandbox_log = sandbox_log[:MAX_SANDBOX_LOG]
        fr.sandbox_result = "passed" if passed else "failed"
        await db.commit()

        # Continue to PR even on sandbox failure — let the reviewer decide.
        if not passed:
            _restore_repo(repo_dir, base_branch)

        # ── Step 5: Git push ──────────────────────────────────────────────
        await _set_status(fr, "pushing", db)
        try:
            github_token = decrypt(us.github_token_encrypted)
        except Exception:
            await _fail(fr, "GitHub token not configured or decryption failed.", db)
            return

        try:
            commit_msg = f"feat: {fr.description[:72]}\n\nAuto-generated by ARMA"
            default_branch = await get_default_branch(github_token, repo.full_name)
            push_fix_branch(
                repo_dir=repo_dir,
                branch_name=fr.branch_name,
                base_branch=default_branch,
                changed_files=list(patches.keys()),
                file_updates=patches,
                commit_message=commit_msg,
                github_token=github_token,
                remote_url=repo.clone_url,
            )
        except Exception as exc:
            await _fail(fr, f"Git push failed: {exc}", db)
            return

        # ── Step 6: Create GitHub PR ──────────────────────────────────────
        try:
            plan_summary = "\n".join(
                f"- **{p['action']}** `{p['file_path']}`: {p['description']}"
                for p in plan
            )
            sandbox_note = (
                f"✅ Tests passed" if fr.sandbox_result == "passed"
                else f"⚠️ Sandbox: {fr.sandbox_result or 'unknown'}"
            )
            pr_body = (
                f"## Feature Request\n\n"
                f"{fr.description}\n\n"
                f"## Implementation Plan\n\n"
                f"{plan_summary}\n\n"
                f"---\n"
                f"{sandbox_note}\n\n"
                f"*Auto-generated by [ARMA](https://github.com) 🤖*"
            )
            pr_title = f"feat: {fr.description[:60]}"

            pr_number, pr_url = await create_github_pr(
                token=github_token,
                full_name=repo.full_name,
                head_branch=fr.branch_name,
                base_branch=default_branch,
                title=pr_title,
                body=pr_body,
            )
        except Exception as exc:
            await _fail(fr, f"PR creation failed: {exc}", db)
            return

        fr.github_pr_number = pr_number
        fr.github_pr_url = pr_url
        fr.status = "pr_opened"
        await db.commit()
        logger.info("[feature] PR opened: %s", pr_url)


# ── Helpers ───────────────────────────────────────────────────────────────────

async def _get_fr(fr_id: str, db: AsyncSession) -> FeatureRequest | None:
    return (
        await db.execute(select(FeatureRequest).where(FeatureRequest.id == fr_id))
    ).scalar_one_or_none()


async def _get_repo(repo_id: str, db: AsyncSession) -> Repo | None:
    return (
        await db.execute(select(Repo).where(Repo.id == repo_id))
    ).scalar_one_or_none()


async def _get_settings(user_id: str, db: AsyncSession) -> UserSettings | None:
    return (
        await db.execute(select(UserSettings).where(UserSettings.user_id == user_id))
    ).scalar_one_or_none()


async def _set_status(fr: FeatureRequest, status: str, db: AsyncSession) -> None:
    fr.status = status
    await db.commit()
    logger.info("[feature] %s → %s", fr.id, status)


async def _fail(fr: FeatureRequest, reason: str, db: AsyncSession) -> None:
    fr.status = "failed"
    fr.error_msg = reason
    await db.commit()
    logger.warning("[feature] %s failed: %s", fr.id, reason)
